# Generated by Django 5.2 on 2025-05-21 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no06', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributiondata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='distributiondata',
            name='cluster',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distributiondata',
            name='person_idx',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distributiondata',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='no06.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='distributiondata',
            unique_together={('video', 'person_idx', 'timestamp')},
        ),
    ]
