# Generated by Django 5.2 on 2025-05-21 05:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no06', '0002_alter_distributiondata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributiondata',
            unique_together={('video', 'timestamp')},
        ),
        migrations.AlterField(
            model_name='distributiondata',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dists', to='no06.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='distributiondata',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='distributiondata',
            name='person_idx',
        ),
    ]
